# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyepi',
                'doc_host': 'https://slee5777.github.io',
                'git_url': 'https://github.com/slee5777/pyepi',
                'lib_path': 'pyepi'},
  'syms': {'pyepi.core': {'pyepi.core.foo': ('core.html#foo', 'pyepi/core.py')}}}
