# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/22_Moving_averages.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/22_Moving_averages.ipynb 3
import pandas as pd
import numpy as np
from scipy import stats
from IPython.core.interactiveshell import InteractiveShell 
import matplotlib.pyplot as plt
import matplotlib.style as style
